name: parquet-explorer
base: core24
version: '0.2.1'
summary: A simple Parquet file viewer
description: |
  A PyQt6 based application to view and explore Parquet files.
  Features include opening parquet files and viewing them in a table.

grade: devel # Change to 'stable' for release
confinement: strict
license: MIT
website: https://github.com/NandaKumarMatha/parquet-data-explorer
source-code: https://github.com/NandaKumarMatha/parquet-data-explorer
issues: https://github.com/NandaKumarMatha/parquet-data-explorer/issues
icon: snap/gui/icon.png

apps:
  parquet-explorer:
    common-id: parquet-explorer
    command: bin/parquet-explorer

    plugs: [home, desktop, desktop-legacy, wayland, x11, opengl, removable-media]
    extensions: [gnome]
    environment:
      # Ensure python can find site-packages
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12/site-packages
      # Prevent GIO from loading libproxy module which causes errors in snap
      GIO_EXTRA_MODULES: ""
      # Use Qt's native platform theme instead of portal-based dialogs
      QT_QPA_PLATFORMTHEME: ""
      # Suppress GTK accessibility module warnings
      GTK_A11Y: none

parts:
  parquet-explorer:
    plugin: python
    source: .
    python-packages:
      - PyQt6
      - pyarrow
      - pandas
      - qdarkstyle
      - matplotlib
    stage-packages:
      - libpython3-stdlib
      - libpython3.12-minimal
      - libpython3.12-stdlib
